# Generated by Django 5.0.1 on 2024-01-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='click_counter',
            new_name='ClickCounter',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
