# Generated by Django 5.0.1 on 2024-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_rename_click_counter_clickcounter_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickcounter',
            old_name='route_126',
            new_name='clicks',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_129',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_135',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_139',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_140',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_141',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_150',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_151',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_152',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_153',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_154',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_155',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_17',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_3',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_30',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_302',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_309',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_32',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_34',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_39',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_4',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_40',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_41',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_48',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_49',
        ),
        migrations.RemoveField(
            model_name='clickcounter',
            name='route_5',
        ),
        migrations.AddField(
            model_name='clickcounter',
            name='route_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
